### PR TITLE
[ISSUE #30] modify mappers and add test

### PR DESCRIPTION
**Pull request by Lambert-Rao**
improved connection, connector, client, meta, health mappers and add their unit tests.

### CODE REVIEW

**Comment by Pil0tXia** [comment]
plz check ci

**Comment by Lambert-Rao** [comment]
CI failed for database test, I have tested them successfully locally, if unit tests are still unavaiiable, I will remove them.

**Comment by Pil0tXia** [comment]
@Lambert-Rao 

You may pull mysql docker image in Github workflow to run unit tests.

**Comment by Pil0tXia** [comment]
Please submit the PR to `dev` branch instead of `develop` branch.

I should have changed this PR's merge destination to `dev` before deleting `develop` branch.

**Comment by Pil0tXia** [comment]
Besides, you may change the database username and password to `root` and `password` in config to run unit tests after https://github.com/apache/eventmesh-dashboard/issues/32 has accomplished.

**Comment by Lambert-Rao** [comment]
> Besides, you may change the database name, username and password to `EVENTMESH_DASHBOARD`, `root` and `password` in config to run unit tests after #32 has accomplished.

@Pil0tXia
I have used `eventmesh-dashboard-test` as the test database name, is there a specific reason for using `EVENTMESH_DASHBOARD`? If not, I would edit your ci file.
Also, should the test database host be `localhost`?

**Comment by Pil0tXia** [comment]
Using `-` in the database name is not a best practice as it is recommended to use `_`.

You can try `localhost` first and see if the application can establish a connection with the container. If it fails, we need to set a `MYSQL_ADDR` environment variable and use `127.0.0.1` as the MySQL host in GitHub Actions.

**Pull request closed without merging**
